
image: continuumio/miniconda3

stages:
 - test

# test environment setup in the server image
test-env:
  stage: test
  image: $CI_REGISTRY/satomi/seg-serve/server:master
  script:
    - conda env create -f conda.yaml

test-local:
  variables:
    CACHE_FOLDER: /builds/cache
    CONDA_ENV: "mmdet-executor"
  stage: test
  image: $CI_REGISTRY/satomi/seg-serve/server:master
  tags:
  - big-ram
  script:
    - rm -rf ${CACHE_FOLDER}
    - mkdir ${CACHE_FOLDER}
    - source ~/.bashrc
    - conda env create -f conda.yaml
    - conda activate mmdet-executor
    - pip install coverage
    - python -m unittest tests/test_local.py
#    - python -m coverage run --source=./ -m unittest tests/test_local.py
#    - coverage xml
  after_script:
    - rm -r ${CACHE_FOLDER}
  artifacts:
    reports:
      cobertura: coverage.xml

# execute the segmentation prediction with a test image
test-online:
  variables:
    SERVICE_LOG_NAME: "/builds/service-logs/logs-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}.txt"
    FF_NETWORK_PER_BUILD: "true"     # activate container-to-container networking
    CONDA_ENV: "mmdet-executor"
  stage: test
  tags:
    - big-ram
  services:
    - name: $CI_REGISTRY/satomi/seg-serve/server:master
      alias: segserve
      entrypoint:
      - /bin/bash
      command:
      - -c
      - "echo Log dir: ${SERVICE_LOG_NAME}; mkdir -p /builds/service-logs; source /home/appuser/.bashrc; uvicorn --host 0.0.0.0 --port 80 main:app 2>&1 | tee ${SERVICE_LOG_NAME}"

  script:
    - echo "Log dir ${SERVICE_LOG_NAME}"
    - |
      function section_start() {
        echo -e "\e[0Ksection_start:`date +%s`:service_logs[collapsed=true]\r\e[0KService logs"
      }

      function section_end() {
        echo -e "\e[0Ksection_end:`date +%s`:service_logs\r\e[0K"
      }
    - |
      (tail -f -n +1 "${SERVICE_LOG_NAME}" | awk '{print "[service-logs]: " $0}' &)
    - conda install mamba -c conda-forge
    - mamba env create -f conda.yaml
    - conda run -n ${CONDA_ENV} pip install requests pillow coverage
    - conda run -n ${CONDA_ENV} python -m unittest tests/test_online.py
#    - conda run -n ${CONDA_ENV} python -m coverage run --source=./ -m unittest tests/test_local.py
#    - conda run -n ${CONDA_ENV} coverage xml

  after_script:
    - rm ${SERIVCE_LOG_NAME}
  artifacts:
    reports:
      cobertura: coverage.xml
      