stages:
 - test-env

# test environment setup in the server image
test-env:
  stage: test-env
  image: $CI_REGISTRY/j.seiffarth/serve-segmentation/server:experimental
  script:
    - conda env create -f conda.yaml 