name: mmdet-executor
channels:
  - pytorch
  - conda-forge
  - fastai
  - anaconda
dependencies:
  - python=3.8.5
  - torchvision
#  - torchaudio
#  - cudatoolkit=11.0.221
  - opencv-python-headless=4.5.4.58
  - numpy=1.21.2
  - pip
  - pip:
    - mlflow
    - --find-links https://download.pytorch.org/whl/cu111/torch_stable.html
    - torch==1.9.0+cu111
    - torchaudio==0.9.0
    - torchvision==0.10.0+cu111
    - --find-links https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/in>
    - mmcv-full==1.3.9
    - mmdet==2.15.1
    - --extra-index-url https://gitlab+deploy-token-1:j5NttmjXZryvgdNbh_iw@jugit.fz-juelich.de/api/v4/projects/4884/packages/pypi/simple
    - acia==0.1.4

