name: mmdet-executor
channels:
  - pytorch
dependencies:
  - python=3.8.11
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip
  - pip:
    - mlflow
#    - --find-links https://download.pytorch.org/whl/cu111/torch_stable.html
#    - --find-links https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/in>
#    - mmcv-full==1.3.9
#    - opencv-python==4.5.3.56
#    - opencv-python-headless==4.5.3.56
    - --extra-index-url https://gitlab+deploy-token-1:j5NttmjXZryvgdNbh_iw@jugit.fz-juelich.de/api/v4/projects/4884/packages/pypi/simple
    - acia==0.1.2

