name: mmdet-executor
channels:
  - pytorch
  - conda-forge
  - fastai
  - anaconda
dependencies:
  - python=3.8.5
  - pytorch=1.9.0
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - opencv-python-headless=4.5.4.60
  - numpy=1.21.2
  - git=2.33.1
  - gcc=11.2.0
  - gxx_linux-64=11.2.0
  - cmake=3.22.1
  - pip
  - pip:
    - mlflow==1.22.0
#    - opencv-python-headless==4.5.4.60
#    - --find-links https://download.pytorch.org/whl/cu111/torch_stable.html
#    - torch==1.9.0+cu111
#    - torchaudio==0.9.0
#    - torchvision==0.10.0+cu111
    - --find-links https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html
    - mmcv-full==1.3.9
    - mmdet==2.15.1
    - --extra-index-url https://gitlab+deploy-token-1:j5NttmjXZryvgdNbh_iw@jugit.fz-juelich.de/api/v4/projects/4884/packages/pypi/simple
    - acia==0.2.15
    - validators